//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestClient.SoapService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoapService.ISOAPRESTDemo")]
    public interface ISOAPRESTDemo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPRESTDemo/EchoWithGet", ReplyAction="http://tempuri.org/ISOAPRESTDemo/EchoWithGetResponse")]
        string EchoWithGet(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISOAPRESTDemo/EchoWithPost", ReplyAction="http://tempuri.org/ISOAPRESTDemo/EchoWithPostResponse")]
        string EchoWithPost(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISOAPRESTDemoChannel : TestClient.SoapService.ISOAPRESTDemo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SOAPRESTDemoClient : System.ServiceModel.ClientBase<TestClient.SoapService.ISOAPRESTDemo>, TestClient.SoapService.ISOAPRESTDemo {
        
        public SOAPRESTDemoClient() {
        }
        
        public SOAPRESTDemoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SOAPRESTDemoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPRESTDemoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SOAPRESTDemoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string EchoWithGet(string message) {
            return base.Channel.EchoWithGet(message);
        }
        
        public string EchoWithPost(string message) {
            return base.Channel.EchoWithPost(message);
        }
    }
}
